### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by entwanne** [entwanne/cours-python3-poo#1]
- [ ] La dynamique des propriétés: remplacer « chaque fois qu'on appelle picture » par « chaque fois qu'on accède à picture ».
- [ ] Plus d'égalité dans les genres des exemples (moins de john et plus de jude)
- [ ] Intégrer remarques de <https://openclassrooms.com/forum/sujet/c-et-c>
- [ ] Intégrer _patterns_ <https://python-patterns.guide/>
- [ ] Module dataclasses : brève présentation, annotations sur types, `asdict`
- [ ] Types Enum (module `enum`)
- [ ] Moins de classes abstraites et plus de protocoles
- [ ] Autres outils de la lib standard liés à la POO :
    - [ ] collections.abc
    - [ ] socketserver
    - [ ] http.server
    - [ ] unittest
- [ ] Utiliser un SimpleNamespace plutôt que définir une classe User dans le 1er chapitre ?
- [ ] changer exemple module crypt (non compatible Windows) ? <https://zestedesavoir.com/forums/sujet/13894/module-crypt-sous-windows/>
- [ ] Héritage coopératif : "Right. Multiple inheritence in Python is **cooperative** -- all of the classes in question have to work together. If they don't, as A and B don't, bad things happen." (<https://mail.python.org/archives/list/python-ideas@python.org/message/HVATCZIKQ642LF7IIB76S67EY3FVOLMV/> / <https://rhettinger.wordpress.com/2011/05/26/super-considered-super/>)
- [ ] `__init_subclass__`
- [ ] Présenter tous les opérateurs et leur méthode spéciale

---

- [ ] Retour etherpin <https://zestedesavoir.com/tutoriels/1253/la-programmation-orientee-objet-en-python/?page=1#p255691>
> Bel effort, merci. Toutefois, ce contenu m’a rapidement largué. J’aurais eu besoin de plus d’exemples, avec des commentaires dans les codes proposés.
> Autant on peut apprendre Python avec le monumental "Un zeste de python", autant ce contenu ne m’a pas permis de pouvoir (enfin) m’approprier la programmation objet.
